### ISSUE TITLE
Wrong assumptions for the value of argc (and possibly argv)

### ISSUE THREAD

**Issue by BrunoASMauricio** [foss-for-synopsys-dwc-arc-processors/newlib#25]
The following tests are failing on baremetal, for both NSIM and QEMU (when using nsim.specs) : gcc.dg/tree-prof/val-prof-8.c, gcc.dg/tree-prof/val-prof-9.c, gcc.dg/tree-prof/pr79587.c

This is because they assume an argc of 1 for the main functions' return (and consequent exit) to be 0.

NSIM has hl.spec to setup appropriate main arguments, but for nsim.spec (the currently used specification), the existing placeholder sets both argc and argv to 0.

This makes the tests abort unnecessarily.

Example:

FAIL: gcc.dg/tree-prof/pr79587.c execution,    -fprofile-generate -D_PROFILE_GENERATE

```
...
unsigned long
__attribute__((noinline))
test(unsigned long v, unsigned long v2){
  unsigned long x = v % v2;
  return x;
}

int main(int argc, char **argv){
  unsigned long r = 0;
  for (int i = 0; i < 100; i++)
    r += test(argc, global);                   <------ Here
  if (r != 100)
    __builtin_abort ();
  return 0;
}
```

A simple debug test case like this showcases the source of the issue.
```
#include <stdio.h>
int main(int argc, char ** argv){
    printf("%d %p", argc, argv);
}
```
Propper argc/argv should in the very least return a number different from 0 and a valid pointer to char**

**Comment by BrunoASMauricio** [comment]
Proposed solution in d169984cba9072c94121279909204d953b9ceb5f by inserting an argc of 1 and a static "baremtal" string into argv[0]

**Comment by abrodkin** [comment]
I'd like to really figure out if there're any requirements for amount of input arguments from the C language perspective. And from https://photolens.tech/can-argc-be-zero-on-a-posix-system/ I may conclude that it's totally OK. That said, please fix the test, not Newlib.

**Comment by BrunoASMauricio** [comment]
Hello @abrodkin !
I perfectly understand your concern.

The reason I chose to alter the crt0 instead of the test is because I understand the consequences of changing the argc and argv in crt0 for baremetal, but not the consequences of the changes to the test, as it seems to be very compiler optimization oriented.

As such I thought it would be best to simply insert dummy, but functionally correct values into argc and argv instead of altering a test without fully understanding that changes' consequences.

I know it might seem paranoid, as in the end the changes to the test would simply be changing a variable into the value it always has (in this case), but I doubt the person who wrote the test added (argc - 1) instead of just 0, and argc instead of just 1 for no reason whatsoever.

With that in mind I would ask that either, if you're comfortable with it, you give me the go ahead to do the aforementioned changes in the tests, or that we invite someone more knowledgeable in this matter to check if such a change would impact the veracity of the test.

In the meantime, I will go ahead and make the changes in a separate branch and link them into this issue.

**Comment by BrunoASMauricio** [comment]
Changes are in the https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/163bd2fb0ba92de84a13bf3cdd8e116e44923117 commit of the https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/ repository

**Comment by abrodkin** [comment]
> I know it might seem paranoid, as in the end the changes to the test would simply be changing a variable into the value it always has (in this case), but I doubt the person who wrote the test added (argc - 1) instead of just 0, and argc instead of just 1 for no reason whatsoever.

You might be surprised, but sometimes even gurus make funny things, so it could have been a spello, wrong assumption or indeed some idea. So I'd suggest to raise that question on GCC mailing list preferably CC'ing that change author.

> With that in mind I would ask that either, if you're comfortable with it, you give me the go ahead to do the aforementioned changes in the tests, or that we invite someone more knowledgeable in this matter to check if such a change would impact the veracity of the test.

And note I'm not an owner of GCC port (it's @claziss just in case) so it's more of a drive by review with some concerns from my PoV. But since we're talking about open source project, nobody can stop you from doing changes in your own branch ;)
