### ISSUE TITLE
Reviewing a branch for pushing to upstream

### ISSUE THREAD

**Issue by kolerov** [foss-for-synopsys-dwc-arc-processors/newlib#57]
I update a branch for pushing ARC Classic (ARCv1/2) code to the upstream: https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/tree/arc-classic-to-upstream. It's composed from `arc64` branch. It contains 2 commits which are not intended to be pushed:

1. [test: [DO NOT UPSTREAM] Don't run atexit.exp test for boards with GDB.](https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/commit/051d3dd7e2d516e4b61b920ea433472985a74cce)
2. [test: [DO NOT UPSTREAM] Change LDFLAGS to ldflags](https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/commit/16cd9cf11d7b076707ad039a3856d8ca589107ca) 

It would be reasonable to verify and push it before the next ARC toolchain release.

**Comment by shahab-vahedi** [comment]
`s/2023/2024/g`

**Comment by kolerov** [comment]
@shahab-vahedi @abrodkin 

I've updated the branch:

1. Updated years and emails.
2. Added a comment for "atexit" commit.
3. Updated `_exit` in UART 8250 code - it must not ignore a return value since `_exit_halt` from `crt0.S` accepts `r0` as a return value. It means that a return value for an application is stored in `r0` when a board is halted. I am verifing it on HSDK.
4. Merged commits for `Makefile.inc` and `Makefile.in`. I think that they may be put in a separate large commit otherwise those changes may be too sparsed and hard to manage while upstreaming...

**Comment by kolerov** [comment]
Yes, I confirm that `_exit_halt` really accepts an exit code.

**Comment by kolerov** [comment]
@shahab-vahedi I pushed a temporary commit with a refactored `uart-8250.c`: https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/blob/arc-classic-to-upstream/libgloss/arc/uart-8250.c. Now it has clearer structure, defines and naming.

**Comment by shahab-vahedi** [comment]
> @shahab-vahedi I pushed a temporary commit with a refactored `uart-8250.c`: https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/blob/arc-classic-to-upstream/libgloss/arc/uart-8250.c. Now it has clearer structure, defines and naming.

It looks much better. I have only one [comment](https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/commit/3e94fb1b1e957dc108638def3bbc393098f254be#r141478240).

**Comment by kolerov** [comment]
@shahab-vahedi I made corresponding changes. Could you review it again?

**Comment by shahab-vahedi** [comment]
All's good. thank you!

**Comment by kolerov** [comment]
Patches are successfully pushed to upstream.
