### ISSUE TITLE
libgloss implementation to support nSIM

### ISSUE THREAD

**Issue by fbedard** [foss-for-synopsys-dwc-arc-processors/newlib#9]

**Comment by abrodkin** [comment]
@claziss @shahab-vahedi may we close this one given we do support nSIM since https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/commit/acdfcb0a0af54715bc37ed1c767bfe901b679357#diff-6ae3cbef94b8177e0ab03edc72497f05?

**Comment by claziss** [comment]
It is not yet added. It is about supporting native nsim Host I/O in the same way as mwdt does.

**Comment by abrodkin** [comment]
I guess once we have functional QEMU this won't be needed any longer, right?

**Comment by claziss** [comment]
Dupicate issue: mwdt host i/o support.
